Bookyar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('book/', include('books.urls')),
    path('cart/', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:book_id>/', views.add_to_cart_view, name='add_cart'),
    path('remove/<int:book_id>/', views.remove_cart_view, name='remove_cart'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
]

cart/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .cart import Cart


class Order(models.Model):

    first_name = models.CharField(_('first_name'), max_length=50)
    last_name = models.CharField(_('last_name'), max_length=50)
    address = models.CharField(_('address'), max_length=500)
    phone_number = models.CharField(_('phone_number'), max_length=12)
    email = models.EmailField(_('email'))
    description = models.TextField(_('your note'), null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} - {self.last_name} - {self.address}"

    class Meta:
        verbose_name_plural = _('Orders')

cart/forms.py
from django import forms

from cart.models import Order


class AddToCartBookForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 30)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone_number', 'email', 'description', ]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy

from books.models import Book
from .cart import Cart
from .forms import AddToCartBookForm, OrderForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from .models import Order


@login_required
def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['book_update_quantity_form'] = AddToCartBookForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })

    return render(request, 'cart/cart_detail.html', {'cart': cart})


@require_POST
def add_to_cart_view(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)

    form = AddToCartBookForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']

        cart.add(book, quantity, replace_current_quantity=cleaned_data['inplace'])

    return redirect('cart:cart_detail')


def remove_cart_view(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)

    return redirect('cart:cart_detail')


class Checkout(CreateView):
    model = Order
    template_name = 'cart/checkout.html'
    form_class = OrderForm
    success_url = reverse_lazy('home')

cart/templates/cart/cart_detail.html
{% load static %}
{% load i18n %}

{% load humanize %}
{% load translation_number %}


<!-- Vendor CSS -->
<link rel="stylesheet" href="{% static 'css/vendor.css' %}">

<!-- style css -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<link rel="stylesheet" href="{% static 'css/_base.css' %}">

{% include 'pages/header-refrences.html' %}

<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
    <div class="page-content-inner ptb--80">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-md--50">
                    <form class="cart-form" action="#">
                        <div class="row no-gutters">
                            <div class="col-12">
                                <div class="table-content table-responsive">
                                    <table class="table text-center">
                                        <thead>
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th>{% translate 'book image' %}</th>
                                            <th>{% translate 'book title' %}</th>
                                            <th>{% translate 'book discount' %}</th>
                                            <th>{% translate 'number' %}</th>
                                            <th>{% translate 'total' %}</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in cart %}
                                            <tr>
                                                <td class="product-remove text-left"><a
                                                        href="{% url 'cart:remove_cart' item.book_obj.id %}"><img
                                                        src="{% static 'icons/close.png' %}"
                                                        style="height: 20px; width: 20px;" alt=""></a></td>
                                                <td class="product-thumbnail text-left">
                                                    <img src="{{ item.book_obj.image.url }}"
                                                         style="height: 70px; width: 70px;"
                                                         alt="Product Thumnail">
                                                </td>
                                                <td class="product-name wide-column">
                                                    <h3>
                                                        <a href="{{ item.book_obj.get_absolute_url }}">{{ item.book_obj.title }}</a>
                                                    </h3>
                                                </td>
                                                <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.book_obj.discount|intcomma:False|translate_number }} {% translate '$' %}</span>
                                                            </span>
                                                </td>
                                                <td class="product-quantity">
                                                    <form action="{% url 'cart:add_cart' item.book_obj.id %}"
                                                          method="post">
                                                        {% csrf_token %}
                                                        <div class="quantity">
                                                            <input type="number" class="quantity-input" name="quantity"
                                                                   id="qty-1"
                                                                   value="{{ item.quantity }}" min="1">
                                                        </div>
                                                        {{ item.book_update_quantity_form.inplace }}
                                                        <button class="small" type="submit"><img
                                                                src="{% static 'icons/refresh.png' %}"
                                                                style="width: 20px; height: 20px;" alt=""></button>
                                                    </form>
                                                </td>
                                                <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price|intcomma:False|translate_number }} {% translate '$' %}</span>
                                                            </span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="cart-collaterals">
                        <div class="cart-totals">
                            <div class="cart-calculator">

                                <div class="cart-calculator__item order-total">
                                    <div class="cart-calculator__item--head">
                                        <span>{% translate 'total price' %}</span>
                                    </div>
                                    <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{ cart.get_total_price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                                </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'cart:checkout' %}" class="btn btn-danger">
                            {% translate 'checkout' %}
                        </a>
                    </div>
                </div>
                <div>
                    <a class="btn btn-warning" href="{% url 'home' %}"><p>{% translate 'return to home' %}</p>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>


{% include 'pages/footer.html' %}
{% include 'pages/footer-refrences.html' %}

cart/templates/cart/checkout.html
{% load static %}
{% load i18n %}
{% load humanize %}
{% load translation_number %}
{% load crispy_forms_tags %}

{% include 'pages/header-refrences.html' %}

<!-- Vendor CSS -->
<link rel="stylesheet" href="{% static 'css/vendor.css' %}">

<!-- style css -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<link rel="stylesheet" href="{% static 'css/_base.css' %}">

<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
    <div class="page-content-inner">
        <div class="container">
            <div class="row pt--50 pt-md--40 pt-sm--20"></div>
            <div class="row pb--80 pb-md--60 pb-sm--40">
                <!-- Checkout Area Start -->
                <div class="col-lg-6">
                    <div class="checkout-title mt--10">
                        <h2>{% translate 'order detail' %}</h2>
                    </div>
                    <div class="checkout-form">
                        <form action="#" class="form form--checkout" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div>
                                <button class="btn btn-primary py-3 px-5"
                                        type="submit">{% translate 'Send Message' %}</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-xl-5 offset-xl-1 col-lg-6 mt-md--40">
                    <div class="order-details">
                        <div class="checkout-title mt--10">
                            <h2>{% translate 'your order' %}</h2>
                        </div>
                        <div class="table-content table-responsive mb--30">
                            <table class="table order-table order-table-2">
                                <thead>
                                <tr>
                                    <th>{% translate 'book' %}</th>
                                    <th class="text-right">{% translate 'total price' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in cart %}
                                    <tr>
                                        <th>{{ item.book_obj.title }}
                                            (<strong><span>&#10005;</span>{{ item.quantity|translate_number }}</strong>)
                                        </th>
                                        <td class="text-right">{{ item.total_price|intcomma:False|translate_number }} {% translate '$' %}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr class="cart-subtotal">
                                    <th>{% translate 'total' %}</th>
                                    <td class="text-right">
                                        {{ cart.get_total_price|intcomma:False|translate_number }}{% translate '$' %} </td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="checkout-payment">
                            <h2 class="py-5">{% translate 'Payment method' %}</h2>
                            <form action="#" class="payment-form">
                                <div class="payment-group mb--10">
                                    <div class="payment-radio">
                                        <input type="radio" value="bank" name="payment-method" id="bank" checked>
                                        <label class="payment-label"
                                               for="cheque">{% translate 'Zarin Pal online portal' %}</label>
                                    </div>
                                </div>
                            </form>

                        </div>

                    </div>
                    <div>
                        <a class="btn btn-outline-primary" href="{% url 'home' %}"><p>{% translate 'return to home' %}</p></a>
                    </div>

                </div>

                <!-- Checkout Area End -->
            </div>
        </div>
    </div>
</div>
<!-- Main Content Wrapper Start -->


{% include 'pages/footer.html' %}
{% include 'pages/footer-refrences.html' %}